# -*- coding: utf-8 -*-
"""find_jar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kkDPfNqneOXZVwdcFMXHkcbTN-k71ne
"""

def find_light_jar(*jars):
    expected_weight = sum(range(1, len(jars) + 1)) * 10
    actual_weight = sum((i + 1) * jars[i] for i in range(len(jars)))
    print(f"Jar {expected_weight - actual_weight} contains the 9g pills.")

find_light_jar(10, 9, 10, 10, 10)